
import { CompetitionEvent, PreferenceVector } from './types';

export const heroEvents: CompetitionEvent[] = [
    {
        id: 'hero-1',
        title: 'Space AI Autonomous Navigation Hackathon',
        description: 'Build autonomous navigation systems for lunar rovers using reinforcement learning and computer vision under extreme terrain constraints.',
        rewardPool: '$500,000',
        tags: ['Space', 'AI'],
        source: 'Kaggle',
        executionType: ['online'],
        difficulty: 8,
        teamConstraints: 'large',
        computedWinRate: 12,
        daysLeft: 14,
        isHighlighted: true,
    },
    {
        id: 'hero-2',
        title: 'Robotic Vibe-Coding Circuit',
        description: 'Design a low-latency control loop for robotic manipulators using vibe-coding principles — fast iteration, tactile feedback, and emergent behavior.',
        rewardPool: '$120,000',
        tags: ['Robotics', 'Vibe-coding'],
        source: 'Google',
        executionType: ['offline'],
        region: { country: 'Switzerland', city: 'Zurich' },
        difficulty: 6,
        teamConstraints: 'small',
        computedWinRate: 28,
        daysLeft: 21,
        isHighlighted: true,
    },
    {
        id: 'hero-3',
        title: 'Quantum ML Benchmark Challenge',
        description: 'Compare classical vs quantum kernel methods on high-dimensional biological and financial datasets. Best hybrid approach wins.',
        rewardPool: '$300,000',
        tags: ['Quantum', 'AI'],
        source: 'Anthropic',
        executionType: ['online'],
        difficulty: 9,
        teamConstraints: 'small',
        computedWinRate: 8,
        daysLeft: 30,
        isHighlighted: true,
    },
    {
        id: 'hero-4',
        title: 'Biotech Sequence Prediction',
        description: 'Predict protein folding and RNA secondary structure from noisy cryo-EM data using self-supervised transformers.',
        rewardPool: '$250,000',
        tags: ['Biotech', 'AI'],
        source: 'Facebook',
        executionType: ['online'],
        difficulty: 9,
        teamConstraints: 'large',
        computedWinRate: 15,
        daysLeft: 45,
        isHighlighted: false,
    },
    {
        id: 'hero-5',
        title: 'AGI Safety Debate Arena',
        description: 'Propose and defend alignment frameworks in a structured debate format against adversarial AI judges. Top submissions get published.',
        rewardPool: '$180,000',
        tags: ['AI', 'Robotics'],
        source: 'Anthropic',
        executionType: ['online'],
        difficulty: 7,
        teamConstraints: 'solo',
        computedWinRate: 22,
        daysLeft: 10,
        isHighlighted: true,
    },
    {
        id: 'hero-6',
        title: 'Space Debris Collision Avoidance',
        description: 'Develop a real-time collision avoidance system for satellite constellations using multi-agent reinforcement learning and orbital mechanics.',
        rewardPool: '$400,000',
        tags: ['Space', 'Quantum'],
        source: 'Kaggle',
        executionType: ['online'],
        difficulty: 8,
        teamConstraints: 'large',
        computedWinRate: 10,
        daysLeft: 60,
        isHighlighted: false,
    },
];

export const gridEvents: CompetitionEvent[] = [
    {
        id: 'g-1',
        title: 'Titanic — ML from Disaster',
        description: 'Predict survival on the Titanic. The classic Kaggle starter competition for ML fundamentals.',
        rewardPool: 'Knowledge',
        tags: ['AI'],
        source: 'Kaggle',
        executionType: ['online'],
        difficulty: 2,
        teamConstraints: 'solo',
        computedWinRate: 85,
        daysLeft: 0,
        isHighlighted: false,
    },
    {
        id: 'g-2',
        title: 'Vibe-Code IDE Plugin Challenge',
        description: 'Build a VS Code extension that converts natural language descriptions into live-editable code snippets using real-time LLM inference.',
        rewardPool: '$30,000',
        tags: ['Vibe-coding', 'AI'],
        source: 'Google',
        executionType: ['online'],
        difficulty: 5,
        teamConstraints: 'small',
        computedWinRate: 35,
        daysLeft: 18,
        isHighlighted: false,
    },
    {
        id: 'g-3',
        title: 'Quantum Error Correction Tournament',
        description: 'Design a surface code decoder that achieves the lowest logical error rate on a simulated superconducting qubit architecture.',
        rewardPool: '$80,000',
        tags: ['Quantum'],
        source: 'Anthropic',
        executionType: ['online'],
        difficulty: 10,
        teamConstraints: 'small',
        computedWinRate: 6,
        daysLeft: 40,
        isHighlighted: true,
    },
    {
        id: 'g-4',
        title: 'Autonomous Greenhouse Challenge',
        description: 'Control temperature, humidity, and light in a simulated greenhouse to maximize crop yield while minimizing water and energy use.',
        rewardPool: '$60,000',
        tags: ['Robotics', 'Biotech'],
        source: 'Facebook',
        executionType: ['online'],
        difficulty: 5,
        teamConstraints: 'small',
        computedWinRate: 42,
        daysLeft: 25,
        isHighlighted: false,
    },
    {
        id: 'g-5',
        title: 'Low-Earth Orbit Traffic Management',
        description: 'Schedule satellite collision avoidance maneuvers across a constellation of 10,000+ LEO satellites using constrained optimization.',
        rewardPool: '$150,000',
        tags: ['Space'],
        source: 'Kaggle',
        executionType: ['online'],
        difficulty: 8,
        teamConstraints: 'large',
        computedWinRate: 14,
        daysLeft: 50,
        isHighlighted: false,
    },
    {
        id: 'g-6',
        title: 'Protein-Ligand Binding Affinity',
        description: 'Predict docking scores for drug candidate molecules against protein targets using geometric deep learning on 3D molecular structures.',
        rewardPool: '$90,000',
        tags: ['Biotech', 'AI'],
        source: 'Google',
        executionType: ['offline'],
        region: { country: 'USA', city: 'Boston' },
        difficulty: 7,
        teamConstraints: 'large',
        computedWinRate: 18,
        daysLeft: 35,
        isHighlighted: false,
    },
    {
        id: 'g-7',
        title: 'Real-Time Speech Emotion Detection',
        description: 'Build a low-latency model that detects emotion from streaming audio in under 50ms. Must generalize across 12 languages.',
        rewardPool: '$45,000',
        tags: ['AI'],
        source: 'Facebook',
        executionType: ['online'],
        difficulty: 6,
        teamConstraints: 'small',
        computedWinRate: 31,
        daysLeft: 12,
        isHighlighted: false,
    },
    {
        id: 'g-8',
        title: 'Hardware Trojan Detection',
        description: 'Identify malicious circuit modifications in IC layout images using anomaly detection and explainable AI techniques.',
        rewardPool: '$200,000',
        tags: ['AI', 'Quantum'],
        source: 'Anthropic',
        executionType: ['offline'],
        region: { country: 'Germany', city: 'Munich' },
        difficulty: 9,
        teamConstraints: 'large',
        computedWinRate: 9,
        daysLeft: 55,
        isHighlighted: true,
    },
];

export const defaultPreferences: PreferenceVector = {
    domains: ['AI', 'Robotics'],
    sources: ['Kaggle'],
    customSources: [],
    allFormalSubSources: [],
    manualLinkNames: [],
    minPrizeTier: '10000',
    executionType: ['online'],
    targetCountry: '',
    targetCity: '',
    teamScale: 'small',
    difficulty: 5,
    showAdvanced: false,
};

export const domainOptions = ['AI', 'Robotics', 'Space', 'Vibe-coding', 'Quantum', 'Biotech'];

export const allFormalSourcesList: string[] = [
    'HuggingFace', 'Devpost', 'Topcoder', 'Codeforces',
    'BeMyApp', 'HackerEarth', 'DrivenData', 'AIcrowd',
    'MLH', 'Kaggle', 'Google', 'Anthropic',
];

export const historyBenchmarks: { label: string; percentage: number }[] = [
    { label: 'ML Engineering', percentage: 30 },
    { label: 'Robotics', percentage: 50 },
    { label: 'AI', percentage: 70 },
];

